Feature/osd viewport
lunit-io/frontend-components pull request #105
Opened 2021-08-30 13:18 UTC by hyunjin-lunit

## 📝 Description

> Add a brief description

## ✔️ PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Chore (non-breaking change which does not affect codebase; Build related changes, version modification, etc.)
- [ ] CI related changes
- [ ] Test Case
- [ ] Performance optimization
- [ ] Site/documentation update
- [ ] Other... Please describe:

## 🎯 Current behavior

It is not updated even if props are changed.
Issue Number: https://app.asana.com/0/1200587746109495/1200834271250862/f

## 🚀 New behavior

You can now use the commitUpdate method to update your props
```
 if (this.options.zoom !== props.zoom) {
    this.viewer.viewport.zoomTo(props.zoom, props.refPoint)
 }
```

## 💣 Is this a breaking change?

- [ ] Yes
- [x] No

> If this PR contains a breaking change, please describe the impact and migration path for existing applications below.

2021-08-31 04:02 UTC, tchung1118 requested changes
ViewportProps type export/import관련 코멘트 말고 특별히 문제는 없어 보이네요

2021-08-31 04:02 UTC, tchung1118 commented on packages/osd-react-renderer/src/elements/Viewport.tsx
> +    this.updateEventHandler('remove')
나중에 개선할 수 있을지는 모르겠는데, eventHandlers에 바뀐게 없으면 이렇게 remove했다가 다시 add하지 않아도 되지 않나 싶네요 ㅋㅋ 나중에 고민해봐요

2021-08-31 04:55 UTC, skpark-lunit commented on apps/osd-viewer-demo/src/App.tsx
> +    event => {
```
({ eventSourse: viewer, degress }) => { ... }
```
이렇게 하면 중간에 const 할당이 필요없겠네요.

현재 master 브랜치에 PR 올릴 때마다 Percy에서 오류 보고 하는 것은 해결하도록 할게요.
해결하기전에는 제가 매번 approve를 해야하는데 불편하게 해서 미안합니다.

2021-08-31 09:03 UTC, hyunjin-lunit commented on apps/osd-viewer-demo/src/App.tsx
> +    event => {
수정했습니다! https://github.com/lunit-io/frontend-components/pull/105/commits/80315f502ac014c9a0d6de26e4013ec2f87384f6

2021-08-31 09:03 UTC, hyunjin-lunit commented on apps/osd-viewer-demo/src/App.tsx
> +import { ViewportProps } from 'packages/osd-react-renderer/src/types'
수정했습니다! https://github.com/lunit-io/frontend-components/pull/105/commits/da1e2a44ca64a18ea0cba4fa70f6f8953e397819

2021-08-31 09:06 UTC, tchung1118 approved these changes

2021-09-01 02:47 UTC, skpark-lunit approved these changes

2021-09-01 03:03 UTC, merged