Feature/insight viewer subpackage #167
lunit-io/frontend-components pull request #173
Opened 2021-12-28 22:41 UTC by skpark-lunit

## 📝 Description
### 라이브러리/subpath로부터 임포트 하기
Issue Number: https://github.com/lunit-io/frontend-components/issues/167

package.exports를 사용하는 방법이 문서 [https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_package_entry_points](https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_package_entry_points)에 나와 있으나, 타입스크립트에서는 기대하는 동작을 하지 않는다. 타입 정의를 찾을 수 없는 문제가 있다.

이 문제에 대해 여기 정리가 잘 되어있다. https://docs.joshuatz.com/cheatsheets/node-and-npm/building-an-npm-package/#approaches-for-working-around-nodejss-root-directory-issue 

사용자에게 노출하려는 디렉토리 구조와 일치하는 패키지를 게시하기 위해
루트에 패키지/subpath에 해당하는 파일을 추가하고, 여기에서 서브 디렉토리의 소스를 다시 export 하는 방식을 선택했다.
- 단점: src/ 와 동일한 레벨에 subpath 파일을 추가하므로 번거롭고, 코드 베이스가 지저분해진다.
- 장점: 쉽고 비교적 손이 덜 간다.
다른 의견 환영합니다. 👂 

### 작업 내용
- 기존의 src/index.ts 대신 src/*.ts를 dist/에 컴파일 하도록 빌드 스크립트 변경 https://github.com/lunit-io/frontend-components/commit/433615d41db1d51379d04e5501d4d7a0e989df7f
  const.ts는 최종 컴파일에 넣지 않기위해 /const 디렉토리로 옮긴다. https://github.com/lunit-io/frontend-components/commit/ac9ab4f9d681ced127258f6ff6dd8cf3a6709339
- src/ 와 동일한 레벨에 expose 할 서브패키지 파일을 추가하고 소스를 여기서 export 한다. contour 패키지는 임의로 만들었다. 추후 제대로 만들 예정. https://github.com/lunit-io/frontend-components/commit/c2cd42f72d3fb525e3e72a2c27ea3de88eed39d5

2021-12-29 23:43 UTC, myjung-lunit approved these changes

2021-12-30 06:06 UTC, deminoth commented
dist의 결과물이 잘 이해가 안 되네요; 번들은 index만 있고 contour는 d.ts만 있는데 저희가 원하는 형태로 번들이 된게 맞을까요?

2022-01-02 07:28 UTC, deminoth commented
mui는 어떻게 하나 찾아봤는데 package.json을 하위 디렉토리 전부에 복붙하고 있네요… 이렇게까지 해야 하나 싶긴 합니다 ㅎㅎ 
https://github.com/mui-org/material-ui/blob/master/scripts/copy-files.js

2022-01-02 23:33 UTC, skpark-lunit commented
> dist의 결과물이 잘 이해가 안 되네요; 번들은 index만 있고 contour는 d.ts만 있는데 저희가 원하는 형태로 번들이 된게 맞을까요?
> 
> 아니면 제가 원하던 결과물을 숙경님에게 제대로 전달하지 못한 것일수도 있겠네요. 저는 Contour 번들 자체를 하위 디렉토리로 분리해서, `import InsightViewer from '@lunit/insight-viewer/InsightViewer';`로 임포트하면 Contour 관련 코드 자체가 앱 번들에는 들어가지 않는 구조를 생각했습니다. (material-ui 등에서 쓰는 방식이요)

제가 작업을 해놓고 잠시 헷갈렸던 부분인데요.
처음에는 package.json의 'exports'로  메인 index.ts와 contour.ts를 dist/에 빌드 결과물을 만들었었어요.
그런데 위 description에서 설명드린대로 타입스크립트에서 이 방식이 현재 지원되지 않네요.
그래서 src/와 같은 레벨에다 contour.ts를 만들어서 이걸 node_modules/의 insight-viewer/contour 경로로부터 임포트 하게 했습니다.
그런데 상엽님 질문을 듣고보니 이렇게 하면 빌드한 결과물이 아닌 원 소스를 가져오게 되고, 그러면 microbundle을 활용하지 못하네요.
'exports'로 멀티 엔트리 빌드(contour 포함)한 후, postbuild 스크립트로 src/와 동등한 레벨에 빌드한 contour.js 및 contour.d.ts 파일을 옮기는 게 어떨까 생각합니다.
지저분하고 귀찮아요. 하지만.
https://blog.izs.me/2013/02/why-no-directorieslib-in-node-the-less-snarky/ 여기를 보면 
이런 문제에 대한 요청에도 기능을 변경하지 않은 이유를 볼 수 있는데요.
'Doing an ugly thing should look ugly.' 라고 하는데, 어쩔 수 없다는 생각이 드네요.

2022-01-02 23:34 UTC, skpark-lunit commented
> mui는 어떻게 하나 찾아봤는데 package.json을 하위 디렉토리 전부에 복붙하고 있네요… 이렇게까지 해야 하나 싶긴 합니다 ㅎㅎ https://github.com/mui-org/material-ui/blob/master/scripts/copy-files.js
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/23083156/79a1d61e-2309-4313-82bc-e5aa96ad0969"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[material-ui/copy-files.js at master · mui-org/material-ui](https://github.com/mui-org/material-ui)**MUI (formerly Material-UI) is the React UI library you always wanted. Follow your own design system, or start with Material Design. - material-ui/copy-files.js at master · mui-org/material-ui

네 저도 그렇게 까진 하고 싶지 않았어요.... 😢

2022-01-03 13:10 UTC, skpark-lunit commented
- 멀티엔트리 빌드 설정 https://github.com/lunit-io/frontend-components/pull/173/commits/fc8bf91e0c142e1fbc2b9112b0770ada07e5cd02
- setupPackage 파일 추가: npm publish 실행을 기존의 프로젝트 루트가 아닌 dist/에서 하도록 준비한다. https://github.com/lunit-io/frontend-components/pull/173/commits/ef2e7b3b4e1651e912eaaa643210f7e4e0967a12
- npm script 업데이트
  - scripty 패키지 추가(npm 명령을 별도의 파일로 추출) https://github.com/lunit-io/frontend-components/pull/173/commits/54623c107a78721fd160e88feb722d82d9e408a6 
  - scripty를 사용해서 npm 스크립트 실행 https://github.com/lunit-io/frontend-components/pull/173/commits/680a640eb765c0b622e146196e67e0fdbc567d3a
  - prepublish/publish 스크립트 추가 https://github.com/lunit-io/frontend-components/pull/173/commits/82bf547e53c895b0663c7ebeba2ed8d4826891ce https://github.com/lunit-io/frontend-components/pull/173/commits/ce8ada8b0a1dd72285f33d367b282bbd3d6a9c66

2022-01-03 13:44 UTC, skpark-lunit commented
**insight-viewer 패키지 publish를 루트 프로젝트 대신 dist/에서 하도록 변경**

[AS-IS]
package.json의
```json
"files": [
  "dist"
],
```
설정으로, 프로젝트 루트에서 publish 할 때, dist/ 디렉토리만 포함하도록 했다.
node_modules/의 @lunit/insight-viewer는 다음과 같다.
<img width="328" alt="무제 2" src="https://user-images.githubusercontent.com/81394944/147936855-89243c10-a2b9-4b57-b501-993148a22d0c.png">

[TO-BE]
prepublish 스크립트 및 setupPackage.ts 설정 파일을 사용하여 
dist/에 빌드한 후,
프로젝트 루트의 .npmignore, README.md, LICENSE, package.json 등을 dist/로 카피한 다음
dist/에서 npm 패키지를 게시한다.
dist/에서 yarn pack을 실행한 결과는 다음과 같다.
<img width="236" alt="무제" src="https://user-images.githubusercontent.com/81394944/147937234-88832381-0168-472e-aaae-0582f9a1d511.png">

2022-01-04 07:28 UTC, deminoth requested changes

2022-01-04 07:28 UTC, deminoth commented on package.json
> +    "scripty": "^2.0.0",
이거 사용은 insight-viewer에서만 하니 그쪽 package.json으로 옮기는게 맞을거같습니다.

2022-01-04 07:28 UTC, deminoth commented on packages/insight-viewer/package.json
> +    "build": "scripty",
스크립트가 compile만 있고 build는 없어서 무심코 입력해봤는데 에러나네요

2022-01-04 07:47 UTC, skpark-lunit commented on package.json
> +    "scripty": "^2.0.0",
rimraf처럼 다른 프로젝트에서도 사용할 수 있으면 좋겠다고 생각해서 루트에 추가했는데,
저만 쓸 것 같긴 하네요. 인사이트 뷰어로 옮겼습니다. https://github.com/lunit-io/frontend-components/pull/173/commits/e3d5fc08b29d9f51f2830bbdb6621ef03cbb8064

2022-01-04 07:49 UTC, skpark-lunit commented on packages/insight-viewer/package.json
> +    "build": "scripty",
네 워크스페이스의 npm build 스크립트는 현재 insight-viewer에서는 쓰고 있지 않고(여기서는 doc이란 명령을 씁니다)
build:osd-react-renderer 명령이 실행되어 에러가 나고 있었네요. 안쓰는 명령인 build 스크립트를 제거했습니다. https://github.com/lunit-io/frontend-components/pull/173/commits/76e462acfad7188a1a9f079df2219e7e757ac6d2

2022-01-04 07:51 UTC, skpark-lunit commented on packages/insight-viewer/package.json
> +    "build": "scripty",
packages/insight-viewer/에서는 yarn build 명령이 정상 동작하는 게 맞습니다.

2022-01-04 07:58 UTC, deminoth commented on packages/insight-viewer/package.json
> +    "build": "scripty",
넵 에러납니다. 그와 별개로 https://github.com/lunit-io/frontend-components/commit/76e462acfad7188a1a9f079df2219e7e757ac6d2 커밋은 좋은 변경같네요.
```
$ scripty
scripty ERR! No script found for npm lifecycle 'build' matching any of:
scripty ERR!   /Users/syyu/repo/frontend-components/packages/insight-viewer/scripts/build+(|.*)
scripty ERR!   /Users/syyu/repo/frontend-components/packages/insight-viewer/scripts/build/index+(|.*)
scripty ERR!   /Users/syyu/repo/frontend-components/packages/insight-viewer/scripts/build/*
scripty ERR!   /Users/syyu/repo/frontend-components/node_modules/scripty/scripts/build+(|.*)
scripty ERR!   /Users/syyu/repo/frontend-components/node_modules/scripty/scripts/build/index+(|.*)
scripty ERR!   /Users/syyu/repo/frontend-components/node_modules/scripty/scripts/build/*
scripty ERR! Either define a script or remove "scripty" from 'scripts.build' in your package.json.
error Command failed with exit code 1.
```

2022-01-04 08:03 UTC, deminoth commented on package.json
> +    "scripty": "^2.0.0",
프로젝트 분리할 경우나 버전 충돌 관리 등 고려하면 해당 프로젝트가 필요로 하는 모든 의존성이 package.json에 포함되는것이 맞겠습니다. 어차피 yarn workspace에서 루트 node_modules로 자동으로 호이스팅 해줄거고요.
같은 이유로 `rimraf` 패키지 의존성도 `insight-viewer`와 `osd-react-renderer`에 추가되는 것이 맞겠습니다.

2022-01-04 08:47 UTC, skpark-lunit commented on packages/insight-viewer/package.json
> +    "build": "scripty",
아.. 정말 scripts/build가 없네요. 중요한 것 찾아주셔서 감사합니다 :bow: 왜 커밋에 빠졌는지 볼게요.

2022-01-04 08:49 UTC, skpark-lunit commented on packages/insight-viewer/package.json
> +    "build": "scripty",
.gitignore의 build 때문이네요 ❗

2022-01-04 08:52 UTC, skpark-lunit commented on packages/insight-viewer/package.json
> +    "build": "scripty",
추가했습니다 .https://github.com/lunit-io/frontend-components/pull/173/commits/8ffcb7ff6b82a6ce2d652de35c9c589dc82c1357

2022-01-04 08:57 UTC, skpark-lunit commented on package.json
> +    "scripty": "^2.0.0",
일리가 있는 말이네요. 현재는 typescript, eslint, husky, prettier 등을 루트 workspace에 설치한 후 이걸 쓰고 있거든요.
타입스크립트 같은 경우는 좀 후회가 됩니다. 각 프로젝트마다 설치하는 게 맞다는 생각이 드네요. 
루트에 이미 설치 했더라도 각 프로젝트에서 다른 버전으로 다시 설치하면 이걸 쓰게 됩니다.
루트에는 모노리포 관련된(lerna, commilint 등)을 제외하고 모두 프로젝트로 옮기는 게 좋을까요?

2022-01-04 08:58 UTC, skpark-lunit commented on package.json
> +    "scripty": "^2.0.0",
rimraf는 이미 osd-react-renderer에서 쓰고 있어서 루트에서 제거하려면 osd 프로젝트에서 자체 설치하도록 말씀드린 후에 제거할게요.

2022-01-04 09:23 UTC, deminoth commented on package.json
> +    "scripty": "^2.0.0",
> 루트에는 모노리포 관련된(lerna, commilint 등)을 제외하고 모두 프로젝트로 옮기는 게 좋을까요?

넵 그게 좋을듯합니다. yarn에서도 그걸 추천해서 루트에서 yarn add 해보시면 경고 표시할거에요.

> rimraf는 이미 osd-react-renderer에서 쓰고 있어서 루트에서 제거하려면 osd 프로젝트에서 자체 설치하도록 말씀드린 후에 제거할게요.

요 부분은 별도 PR로 한번에 변경하고 osd 쪽에서 리뷰만 해주시면 될거같습니다.

2022-01-04 09:53 UTC, deminoth commented on packages/insight-viewer/.npmignore
> +setupPackage.*
혹시 setupPackage.ts 파일을 한 단계 위로 이동하는 방법으로 해결은 어려울까요?

2022-01-04 09:55 UTC, skpark-lunit commented on packages/insight-viewer/.npmignore
> +setupPackage.*
아니요 그래도 됩니다. 순서가 어떤 상관이 있을까요? 이거에 대해서는 아무 생각이 없었네요.

2022-01-05 02:45 UTC, skpark-lunit commented on packages/insight-viewer/.npmignore
> +setupPackage.*
- src/ 바깥으로 setupPackage 파일 옮겼습니다. https://github.com/lunit-io/frontend-components/pull/173/commits/546b29ee790c2a35bbfc438560036c4213959d52
- .npmignore 업데이트 https://github.com/lunit-io/frontend-components/pull/173/commits/38f8a6d6477d41c3a94d9a9b48cf9eac307676f0

2022-01-06 00:56 UTC, deminoth approved these changes

2022-01-06 07:54 UTC, merged

2022-01-07 03:07 UTC, deminoth commented
@skpark-lunit master 머지도 부탁드릴께용