Feature/measurement ruler edit
lunit-io/frontend-components pull request #234
Opened 2022-03-28 09:00 UTC by LTakhyunKim

## 📝 Description

Measurement 의 Ruler mode 에 Edit 기능을 추가했습니다.

Edit 기능을 추가하면서 기존 hook 에 대한 리팩토링도 함께 진행했습니다.
event handling 과 point 관리를 분리하여 하나의 hook 에서 담당하는 일을 분리했습니다.

issue: https://github.com/lunit-io/frontend-components/issues/199

## ✔️ PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Chore (non-breaking change which does not affect codebase; Build related changes, version modification, etc.)
- [ ] CI related changes
- [ ] Test Case
- [ ] Performance optimization
- [ ] Site/documentation update
- [ ] Other... Please describe:

## 🎯 Current behavior

Issue Number: N/A

## 🚀 New behavior

Edit 기능 활성화 및 measurement 선택 시, 양 끝에 edit circle 에 대한 반지름을 정의했습니다. f5e2b7f

select, hover 에 대한 구분을 위해 hover style 을 추가했습니다. 21d1c18
이와 더불어 Edit 기능 대상에 대한 EditPoint type 을 추가했습니다. 7b0b2a5

hover, select, edit 에 대한 props 를 MeasurementViewer, Overlay 에 추가했습니다. e2eda93, 27d9cf1

hover, select measurement 에 대한 값을 useMeasurement 추가했습니다. d02f649

Ruler Edit 중 move 에 대한 위치 값을 계산하는 getMoveRulerPoints util function 을 추가했습니다. 1ca65cf

Measurement 에서 drawing 기능에 대한 point 값을 계산하는 getMeasurementDrawingPoints 를 추가했습니다. 5ccf74b

Measurement 에서 editing 기능에 대한 point 값을 계산하는 getMeasurementEditingPoints 를 추가했습니다. 28fba9a

editing, drawing point 에 대한 값을 관리하는 useMeasurementPointsHandler hook 을 추가했습니다. 5574c2a

mouse event 관리 및 좌표값에 대한 변환을 담당하는 useDrawingHandler hook 을 추가했습니다. a553323

MeasurementDrawer component 에 useMeasurementPointsHandler hook 을 적용했습니다.

> Please describe the behavior or changes this PR adds.

## 💣 Is this a breaking change?

- [ ] Yes
- [x] No

## Comment
리팩토링 시 정리했던 notion 링크 첨부합니다.
기존 문제가 되었던 코드, 문제점, 원래 의도를 비롯한
리팩토링 과정에서 분리한 hook 에 대한 원리 원칙을 정리했습니다. 코드 리뷰 시 참고해주시면 감사하겠습니다.

[기존 hook, 변경(추가) hook 에 대한 원리 원칙 ](https://fair-cork-eef.notion.site/Measurement-90039a4a07984db18821b49def0500f8)

[문제점, 리팩토링 대상에 대한 정리](https://fair-cork-eef.notion.site/useMeasurementDrawing-c3e687e594834bf69b810bf225c75750)

2022-03-28 15:20 UTC, LTakhyunKim commented
기존 가장 하위 레벨 component 인 mode 별 Viewer 에서 pixelToCanvas 로 좌표계를 변경하는 로직을
useDrawingHandler 에서 처리하는 방식으로 수정했습니다.

이를 통해 하위 레벨에서는 좌표계 변경 로직을 제거할 수 있으며, point 에 대한 값 할당을 별도의 로직 없이 바로 할 수 있습니다.

pixelToCanvas 를 useDrawingHandler 에 추가 및 좌표계 변경했습니다.  [b727352](https://github.com/lunit-io/frontend-components/pull/234/commits/b72735248eb7bc22b1f2eb6fb597e514a6dae901)

Viewer, Drawer 에서 불필요한 pixelToCanvas 에 대한 type 선언, 사용 로직 제거했습니다. [48bf5bb](https://github.com/lunit-io/frontend-components/pull/234/commits/48bf5bbb2f1b346a6aaf1247ed1576f092926c90), [327b8bb](https://github.com/lunit-io/frontend-components/pull/234/commits/327b8bb54143c6cd618b49778d8167107ea3a73e)

2022-03-28 23:26 UTC, deminoth commented
새 기능과 리팩토링을 함께 하면 버그가 나기 더 쉽다는 문제가 있죠 ㅎㅎ 새 기능을 짜면서 리팩토링의 실마리가 보이는 경우가 많아서 어렵긴 한데, 가능하면 커밋을 refactor와 feat으로 분리하려고 시도해보세요.

2022-03-29 00:02 UTC, LTakhyunKim commented
> 새 기능과 리팩토링을 함께 하면 버그가 나기 더 쉽다는 문제가 있죠 ㅎㅎ 새 기능을 짜면서 리팩토링의 실마리가 보이는 경우가 많아서 어렵긴 한데, 가능하면 커밋을 `refactor`와 `feat`으로 분리하려고 시도해보세요. 최근에 제가 VIEW에서 했던 시도로는 먼저 커스텀 훅을 분리하고 [60dffb6](https://github.com/lunit-io/insight-view/pull/25/commits/60dffb6bd425bd6b5a19e2b2c14735332aeaf48c) 그 훅에 기능을 추가했네요 [0fa9087](https://github.com/lunit-io/insight-view/pull/25/commits/0fa90876427b23e11502f2617d0da755419f86d7)

좋은 의견 주셔서 감사합니다 :) 말씀해주신 것처럼 이번에 edit 기능을 짜면서 리팩토링 요소들이 보여, 함께 처리하다보니 많은 버그가 있었네요 ㅎㅎ.. 다음부터는 refactor 와 feat 로 구분하도록 노력하겠습니다.

예시를 보면서 느낀 건 useDrawingHandler 와 useMeasurementPointsHandler 를 먼저 분리 후
그 다음에 edit 기능을 천천히 추가하면 좀 더 버그 해결에 있어 좋은 결과를 가져왔을 것 같네요.

2022-03-29 02:01 UTC, myjung-lunit commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
이것도 사소한데.... 
return {startPoint.x, startPoint.y, endPoint.x, endPoint.y} 형태로 작성하면 불필요한 라인을 줄일 수 있을 거 같아요:)

추가로, startPoint 내 포인트 값은 x와 y 일테니, 굳이 StartPointX, StartPointY로 작성하지 않아도 괜찮을 듯 합니다~ startPoint라는 내용이 중복되니까요:)
x, y만 남겨두면, startPoint와 endPoint의 type도 Point 하나로 관리할 수 있구요.

2022-03-29 02:05 UTC, LTakhyunKim commented on apps/insight-viewer-docs/src/containers/Measurement/Drawer/index.tsx
>      wadouri: IMAGES[11],
넵 상수로 정의해서 사용하면 좀 더 명확하고 좋을 것 같네요.
추후 추가되는 예제들에서는 말씀해주신 것처럼 동일한 이미지를 해당 상수 호출해서 사용할 수 있을 것 같구요.
이건 별도의 PR 로 가져가겠습니다~

2022-03-29 02:14 UTC, deminoth commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
민영님 `[startPoint.x, startPoint.y, endPoint.x, endPoint.y]`를 의도하신걸까요?

2022-03-29 02:14 UTC, myjung-lunit commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
맞습니다~ㅎㅎㅎㅎ

2022-03-29 02:17 UTC, deminoth commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
네 사실 좌표를 다루는 코드들은 좌표 집합을 tuple로 표현하는 경우가 많아서, 저희도 따라가면 좋을 것 같습니다. (물론 그런 프로젝트들은 성능때문에 구조체보다는 배열을 사용하는 이유도 있겠지만요)
다만 저희는 타입스크립트를 쓰기 때문에 as [number, number, number, number] 가 붙는 불상사가…

2022-03-29 03:11 UTC, LTakhyunKim commented on apps/insight-viewer-docs/src/containers/Measurement/Drawer/index.tsx
> +  const [isEdit, setIsEdit] = useState(false)
넵 수정하겠습니다.

2022-03-29 03:17 UTC, LTakhyunKim commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +  const { points, setEditTargetPoint } = useMeasurementPointsHandler({
음.. setEditTargetPoint function 의 경우, points 에 대한 핸들링과는 별도로 동작합니다.
points 는 Drawer 에서 사용할 좌표값 배열을 의미하며 
setEditTargetPoint 는 edit 기능 사용 시, ruler 의 경우, start point, end point, line 클릭 여부를
확인해주는 function 입니다. 그렇기에 위와 같이 네이밍을 했던 것이구요.

다만 이렇게 코멘트를 남겨주신 이유에 대해서 생각해보면, 해당 hook 에서 제공하는 funciton 이고,
이에 따라 자연스럽게 points 에 대한 set function 으로 생각하실 수 있네요.

이 부분은 다소 고민이 드네요. 아예 target point 에 대한 function 은 hook 에서 처리하는 것이 아닌,
MeasurementDrawer 에서 useState 로 값을 처리하고 해당 hook 으로 전달하는 방법을 사용하는 방법도
고려하고 있습니다. 이 내용 관련해서 의견 주시면 감사하겠습니다.

2022-03-29 03:25 UTC, myjung-lunit commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +  const { points, setEditTargetPoint } = useMeasurementPointsHandler({
그런 동작이라면 edit 시 호출하는 function을 분리하는 것이 맞지 않을까 합니다.

create와 edit가 다른 point를 사용하는 것은 아니니까요.

const [points, setPoints] = useState<Point>();

// edit인 경우, 아래 function을 사용
const updatePointsByEdit = (point: Point) => {
 setPoint(point);
}

로 하는 것이 points를 업데이트하는 이유에 따라 분기하는 방법이 아닐까 합니다.

2022-03-29 06:24 UTC, LTakhyunKim commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +  const { points, setEditTargetPoint } = useMeasurementPointsHandler({
위 리뷰는 setEditTargetPoint 에 대한 네이밍으로 반영하겠습니다.
네이밍이 다소 모호한 부분이 있어 개발자분들께서 혼동이 올 여지가 있기에, 
이번 PR 에서는 네이밍 변경으로 해결하고자 합니다.

더불어 Edit point set 에 대한 코드는 분리하려 하는데, 현재 PR 에서 리팩토링 및 신규 기능 등
이미 변경 추가된 내용이 많아 이슈 등록 후 별도의 PR 로 가져가겠습니다.

2022-03-29 06:30 UTC, LTakhyunKim commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
startPoint, endPoint 에 대한 별도의 선언을 없애고, index 로 접근하는 방식으로 수정하겠습니다.

더불어 index 로 접근할 경우 x, y 좌표에 대한 명시가 없어, 코드 가독성에 좋지 않은 영향을 줄 것으로 예상되어,
기존 Point 에 대한 type 을 `[number, number]` 에서 `{ x: number y: number }` 로 변경하려 합니다.
다만 위 변경 시 전체적인 코드가 변경되어야하므로 다음 개발 스프린트에서 다루도록 하겠습니다.
이는 이슈 등록 후 따로 진행하겠습니다.

2022-03-29 06:30 UTC, myjung-lunit approved these changes

2022-03-29 06:53 UTC, deminoth commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
> 더불어 index 로 접근할 경우 x, y 좌표에 대한 명시가 없어, 코드 가독성에 좋지 않은 영향을 줄 것으로 예상되어,

사실 그래서 타입스크립트에는 labeled tuple도 있습니다 `[ x: number, y: number ]`

2022-03-29 06:59 UTC, LTakhyunKim commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
> > 더불어 index 로 접근할 경우 x, y 좌표에 대한 명시가 없어, 코드 가독성에 좋지 않은 영향을 줄 것으로 예상되어,
> 
> 사실 그래서 타입스크립트에는 labeled tuple도 있습니다 `[ x: number, y: number ]`

아하... 참고해보겠습니다..!!! 🙏

2022-03-29 07:08 UTC, deminoth requested changes
지금 동작은 클릭으로 선택 → 끝점을 드래그해 수정 → 마우스를 놓으면 해제 인데, 수정 후에도 선택이 해제되지 않는 UI가 더 일반적입니다.
그리고 가능하면 끝점 위에서 커서가 `move`로 바뀌면 좋겠습니다. 지금 커서 위치에서 드래그하면 전체 이동이 될지 끝점만 이동이 될지 알기가 어렵네요.

2022-03-29 07:21 UTC, LTakhyunKim commented
> 지금 동작은 클릭으로 선택 → 끝점을 드래그해 수정 → 마우스를 놓으면 해제 인데, 수정 후에도 선택이 해제되지 않는 UI가 더 일반적입니다. 그리고 가능하면 끝점 위에서 커서가 `move`로 바뀌면 좋겠습니다. 지금 커서 위치에서 드래그하면 전체 이동이 될지 끝점만 이동이 될지 알기가 어렵네요.

넵, 우선 수정 후 선택이 해제되지 않는 UI 의 경우 PR 내용 중 미구현 내용 1번의 measurement edit 후 selected 상태 유지 와 동일한
내용으로 보입니다. 이는 별도의 PR 에서 처리하려 했는데 필요하다면 이번 PR 에서 수정하겠습니다.

더불어 끝점 위에서 커서가 move 로 변경하는 해당 영역에 hover 시 마우스 커서의 모양을 move 로 변경하는 내용이 맞을까요?
![스크린샷 2022-03-29 오후 4 20 47](https://user-images.githubusercontent.com/88369343/160555927-e4f43403-5ab6-431e-a8b5-fde5751ad06e.png)

2022-03-29 07:28 UTC, LTakhyunKim commented on apps/insight-viewer-docs/src/containers/Measurement/Drawer/index.tsx
> +  const [isEdit, setIsEdit] = useState(false)
> MeasurementDrawerProps에는 isEditing으로 prop 이름이 설정되어 있으니 맞추면 좋을 거 같아요.

docs 내 isEdit 에 대한 네이밍 수정했습니다.
isEdit -> isEditing 으로 수정했습니다. [abf3248](https://github.com/lunit-io/frontend-components/pull/234/commits/abf324832620f0d9abff6b9e92187600cd697dbe)

2022-03-29 08:35 UTC, deminoth commented
> 더불어 끝점 위에서 커서가 move 로 변경하는 해당 영역에 hover 시 마우스 커서의 모양을 move 로 변경하는 내용이 맞을까요?

맞습니다. 꼭 move여야 하는건 아니고, 사용자에게 피드백을 주는 것이 목적입니다.

2022-03-29 08:39 UTC, LTakhyunKim commented
> > 더불어 끝점 위에서 커서가 move 로 변경하는 해당 영역에 hover 시 마우스 커서의 모양을 move 로 변경하는 내용이 맞을까요?
> 
> 맞습니다. 꼭 move여야 하는건 아니고, 사용자에게 피드백을 주는 것이 목적입니다.

넵~! 반영하겠습니다.

2022-03-29 08:57 UTC, LTakhyunKim commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +  const { points, setEditTargetPoint } = useMeasurementPointsHandler({
기존 EditPoint 네이밍을 EditMode 로 변경했습니다. [0fce0bb](https://github.com/lunit-io/frontend-components/pull/234/commits/0fce0bb82ae28602b2fe7d7658a0864e75453925)

기존 setEditTargetPoint 를 setMeasurementEditMode 로 변경했습니다. [35c9ffb](https://github.com/lunit-io/frontend-components/pull/234/commits/35c9ffb3f3f369931b70b722db17d648a151dc16)

기존 Point 라는 네이밍이 다소 혼동을 주는 듯하여 Mode 로 변경하는 작업을 진행했습니다.

2022-03-29 09:29 UTC, LTakhyunKim commented on packages/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
> +    return { startPointX, startPointY, endPointX, endPointY }
우선 인덱스로 접근하는 방식을 사용하면서, 굳이 별도의 함수로 접근하는 의미가 많이 줄어든 것 같아,
삭제 후 circle 쪽에서는 points 값을 index 로 접근하는 방식으로 변경했습니다. [08096b9](https://github.com/lunit-io/frontend-components/pull/234/commits/08096b901e9fa768332f850782b47f948be7b0aa)

다만 이 경우 인덱스로 표기한 탓에 가독성이 떨어질 것 같아 우려는 됩니다. 
이에 대한 추가 조치는 circle mode 에 대한 기능 구현 시 함께 개선하려 합니다.

circle 일 경우엔 해당 좌표값 계산을 별도로 해야하기 때문에 util function 에서 게산 후 return value 로
edit point 를 표기할 예정입니다.

2022-03-30 01:45 UTC, LTakhyunKim commented
> > > 더불어 끝점 위에서 커서가 move 로 변경하는 해당 영역에 hover 시 마우스 커서의 모양을 move 로 변경하는 내용이 맞을까요?
> > 
> > 
> > 맞습니다. 꼭 move여야 하는건 아니고, 사용자에게 피드백을 주는 것이 목적입니다.
> 
> 넵~! 반영하겠습니다.

마우스 끝점 기준으로 마우스 커서의 모양을 move 로 변경했습니다. [c24f32f](https://github.com/lunit-io/frontend-components/pull/234/commits/c24f32f35206b4fdc0f42bd18752c02d0392b777)

기타 라인, 텍스트에 hover 시 pointer style 을 반영했습니다. [f62adbd](https://github.com/lunit-io/frontend-components/pull/234/commits/f62adbd0402e165937e3d929a9c32a8a4a7e97be), [7f4d150](https://github.com/lunit-io/frontend-components/pull/234/commits/7f4d150730f8c6d66b4ee788205e4d80b0f2103b)

2022-03-30 04:48 UTC, deminoth commented
> 기타 라인, 텍스트에 hover 시 pointer style 을 반영했습니다. [f62adbd](https://github.com/lunit-io/frontend-components/pull/234/commits/f62adbd0402e165937e3d929a9c32a8a4a7e97be), [7f4d150](https://github.com/lunit-io/frontend-components/pull/234/commits/7f4d150730f8c6d66b4ee788205e4d80b0f2103b)

오 좋은데… 사실 잡아 옮기는 용도로는 `grab`이 있습니다 ㅎㅎ

2022-03-30 04:50 UTC, LTakhyunKim commented
> > 기타 라인, 텍스트에 hover 시 pointer style 을 반영했습니다. [f62adbd](https://github.com/lunit-io/frontend-components/pull/234/commits/f62adbd0402e165937e3d929a9c32a8a4a7e97be), [7f4d150](https://github.com/lunit-io/frontend-components/pull/234/commits/7f4d150730f8c6d66b4ee788205e4d80b0f2103b)
> 
> 오 좋은데… 사실 잡아 옮기는 용도로는 `grab`이 있습니다 ㅎㅎ

오 grab 적용하는 것이 용도에 더 맞겠네요. 적용하겠습니다~

2022-03-30 05:01 UTC, deminoth submitted a review, later dismissed

2022-03-30 05:02 UTC, LTakhyunKim commented
> > > 기타 라인, 텍스트에 hover 시 pointer style 을 반영했습니다. [f62adbd](https://github.com/lunit-io/frontend-components/pull/234/commits/f62adbd0402e165937e3d929a9c32a8a4a7e97be), [7f4d150](https://github.com/lunit-io/frontend-components/pull/234/commits/7f4d150730f8c6d66b4ee788205e4d80b0f2103b)
> > 
> > 
> > 오 좋은데… 사실 잡아 옮기는 용도로는 `grab`이 있습니다 ㅎㅎ
> 
> 오 grab 적용하는 것이 용도에 더 맞겠네요. 적용하겠습니다~

RulerDrawer polyline cursor value 를 `pointer` 에서 `grab` 으로 변경했습니다. [83cf4d2](https://github.com/lunit-io/frontend-components/pull/234/commits/83cf4d28d0b09c251741d8ffc52998194e7cae09)
함께 적용했던 MeasurementViewer 의 cursor 는 `pointer` 로 유지했습니다.
실제로 이동하는 기능을 사용하는 곳은 RulerDrawer 이며 Viewer 에서는 해당 measurement 를 지칭하는 기능이기 때문입니다.

2022-03-30 05:22 UTC, LTakhyunKim commented
> 지금 동작은 클릭으로 선택 → 끝점을 드래그해 수정 → 마우스를 놓으면 해제 인데, 수정 후에도 선택이 해제되지 않는 UI가 더 일반적입니다. 

요청하셨던 수정 후에도 선택이 해제되지 않는 UI 구현을 위해 addDrewMeasurement function 에 조건문을 추가했습니다.
위 조건문을 통해 edit 기능 사용 후 selected mode 가 풀리지 않습니다. [affda08](https://github.com/lunit-io/frontend-components/pull/234/commits/affda08f64785f7812c7ff321559d91d9336ba94)

2022-03-30 06:35 UTC, myjung-lunit commented
탁현님, 배포된 URL로 동작확인했을 때, measurement를 클릭하면, selected가 아니라 delete로 동작하는데 한번 확인해 주실 수 있을까요?

2022-03-30 06:37 UTC, LTakhyunKim commented
> 탁현님, 배포된 URL로 동작확인했을 때, measurement를 클릭하면 selected가 아니라 delete로 동작하는데 한번 확인해 주실 수 있을까요?

민영님~ 혹시 edit mode 스위치 활성화 해주셨을까요?
클릭 이벤트의 경우, edit mode 활성화 여부에 따라 delete mode, edit 기능으로 사용됩니다.

![스크린샷 2022-03-30 오후 3 36 42](https://user-images.githubusercontent.com/88369343/160766947-68416ed6-3139-4454-b88e-5c3d5660c65e.png)

2022-03-30 06:42 UTC, myjung-lunit commented
> 민영님~ 혹시 edit mode 스위치 활성화 해주셨을까요?

아아아.ㅎㅎㅎㅎ

그냥 해서 그랬군요~ 확인했습니다. 감사합니다!

그리고, esc 눌렀을 때는 selected 해지가 아니라 delete로 동작하는데 이건 맞는 동작일까요~?

2022-03-30 06:48 UTC, LTakhyunKim commented
> > 민영님~ 혹시 edit mode 스위치 활성화 해주셨을까요?
> 
> 아아아.ㅎㅎㅎㅎ
> 
> 그냥 해서 그랬군요~ 확인했습니다. 감사합니다!
> 
> 그리고, esc 눌렀을 때는 selected 해지가 아니라 delete로 동작하는데 이건 맞는 동작일까요~?

음.. 그건 의도된 동작은 아닙니다 ㅠ.. 발견해주셔서 감사합니다.
selected 해지가 되는 것이 올바른 동작입니다. 바로 수정하겠습니다~

2022-03-30 07:03 UTC, myjung-lunit approved these changes

2022-03-30 08:00 UTC, LTakhyunKim commented
> > > 민영님~ 혹시 edit mode 스위치 활성화 해주셨을까요?
> > 
> > 
> > 아아아.ㅎㅎㅎㅎ
> > 그냥 해서 그랬군요~ 확인했습니다. 감사합니다!
> > 그리고, esc 눌렀을 때는 selected 해지가 아니라 delete로 동작하는데 이건 맞는 동작일까요~?
> 
> 음.. 그건 의도된 동작은 아닙니다 ㅠ.. 발견해주셔서 감사합니다. selected 해지가 되는 것이 올바른 동작입니다. 바로 수정하겠습니다~

cancelDrawing function 에 위 경우의 수를 방지하기 위한 validation 로직을 추가했습니다. [5265a11](https://github.com/lunit-io/frontend-components/pull/234/commits/5265a11e454ea857f30c16913c606d6e7b184312)
더불어 기존 addDrewMeasurement function 에서 cancelDrawing 을 호출하는 방식인데,
이는 호출하는 영역에서 별도로 cancelDrawing 을 호출하도록 수정했습니다. 
(addDrewMeasurement function 에서 굳이 cancelDrawing 을 호출할 이유가 없기에 위와 같이 변경했습니다.)

기존 mouse leave, esc key event 동작 시 cancelDrawing function 만 호출하는 방식에서
addDrewMeasrement function 도 함께 호출하도록 수정했습니다. [5265a11](https://github.com/lunit-io/frontend-components/pull/234/commits/5265a11e454ea857f30c16913c606d6e7b184312)

위 내용을 반영하여 아래와 같이 동작 flow 로 변경되었습니다.
### 기존 동작
drawing, editing mode 에서 esc keydown 혹은 mouse leave 이벤트 발생 시 대상 measurement 를 삭제한다.

### 현재 변경된 동작
drawing, editing mode 에서 esc keydown 혹은 mouse leave 이벤트 발생 시 당시 measurement 를 drawing 한다.

만약 위 동작 방식이 다소 어색하다면 피드백 부탁드립니다.

2022-03-31 03:43 UTC, LTakhyunKim commented
> ### 기존 동작
> drawing, editing mode 에서 esc keydown 혹은 mouse leave 이벤트 발생 시 대상 measurement 를 삭제한다.
> ### 현재 변경된 동작
> drawing, editing mode 에서 esc keydown 혹은 mouse leave 이벤트 발생 시 당시 measurement 를 drawing 한다.
만약 위 동작 방식이 다소 어색하다면 피드백 부탁드립니다.

위 동작 방식에 대한 추가적인 피드백 없으시면 위 PR 은 머지하겠습니다~ :)

2022-03-31 05:15 UTC, merged