Fix/ handle undefined length
lunit-io/frontend-components pull request #271
Opened 2022-07-26 04:54 UTC by Seunghyeon-lunit

## 📝 Description

1. useImage 에서 사용되던 Image 타입이 실제 데이터와는 다른 부분이 있어서 수정하였습니다.
2. 기존에 포인터 간의 거리를 계산할 때  'PixelSpacing' 을 배율로 사용하였고 없는 경우 undefined 오류가 생겼습니다. 그래서 'PixelSpacing' 이 없는 경우 'ImagerPixelSpacing' 을 확인하여 배율로 사용하고 없다면 별도의 배율을 주지 않습니다.
3. 별도의 배율을 주지않는 경우 단위를 'mm' 에서 'px' 로 변경하였습니다.
4. getLineLength, getCircleRadius 와 같은 유틸 함수들의 경우, 선을 그리는 경우 매우 자주 사용이되는데, 중간에 분기가 좀 많은 것 같아서 후에 useCallBack으로 최적화하기 쉽도록 변경하였습니다.

기타 확인 요청 사항
1. 만약 px 의 경우 소수점 둘째자리까지 나오는게 어색해보여서 px의 경우 정수형태로 표현하는 것이 어떨까요?

## ✔️ PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Chore (non-breaking change which does not affect codebase; Build related changes, version modification, etc.)
- [ ] CI related changes
- [ ] Test Case
- [ ] Performance optimization
- [ ] Site/documentation update
- [ ] Other... Please describe:

## 🎯 Current behavior

> Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: N/A

## 🚀 New behavior

> Please describe the behavior or changes this PR adds.

## 💣 Is this a breaking change?

- [ ] Yes
- [x] No

> If this PR contains a breaking change, please describe the impact and migration path for existing applications below.

2022-07-26 11:38 UTC, deminoth requested changes

2022-07-26 11:38 UTC, deminoth commented on insight-viewer.code-workspace
> +}
이거 vscode 설정파일인가요? 기본적으로 본인 개발환경에서만 사용되는 파일은 커밋하지 말아주시고, 혹시 모두에게 추천하기 위해 커밋할 경우에는 PR에 소개문구 써주세요.

2022-07-26 11:38 UTC, deminoth commented on packages/insight-viewer/src/utils/common/checkImageUnit.ts
> +}
자바스크립트에서만 적용되는 것은 아니고, 현대의 컴퓨팅 환경은 대부분 분기처리에 있어서 대단한 효율을 보여주기 때문에 이 정도 연산은 최적화가 따로 필요 없습니다. useMemo는 프로파일링을 통해 확실히 느리다고 확인한 경우에만 사용해주세요. 오히려 결과를 메모리에 캐시하고 불러오는 동작 때문에 더 느려집니다 ㅎㅎ

2022-07-26 11:38 UTC, deminoth commented on packages/insight-viewer/src/utils/common/calculateDistance.ts
> +    return Math.sqrt(Math.pow(radius, 2) / Math.pow(1, 2))
이 수식 풀어쓰면 그냥 radius네요

2022-07-26 11:38 UTC, deminoth commented on packages/insight-viewer/src/Viewer/RulerViewer/index.tsx
> +  const unit = useMemo(() => checkImageUnit(image), [image])
`unit`은 뷰어에서 매번 확인하지 말고, length와 마찬가지로 그릴 당시에 measurement에 저장해주세요.

2022-07-26 11:38 UTC, deminoth commented on packages/insight-viewer/src/utils/common/getLineLength.ts
> +    const imagerPixelSpacing = currentImage.data.elements.x00181164 as unknown as [number, number]
이거 console.log로 찍어보시면 아시겠지만… 값 안 들어있습니다. 바이트 어레이에서 해당 태그의 위치와 길이가 들어있어요.

2022-07-26 11:38 UTC, deminoth commented on packages/insight-viewer/src/utils/common/getLineLength.ts
> +    const imagerPixelSpacing = currentImage.data.elements.x00181164 as unknown as [number, number]
요 uri 쓰시면 pixelSpacing이랑 imagerPixelSpacing 둘 다 들어있는 dcm 파일로 테스트 가능하니 `checkRulerCalcOption` 쪽에서 pixelSpacing 무시하고 강제로 imagerPixelSpacing 선택해서 확인해보세요.
`wadouri:https://static.lunit.io/fixtures/dcm-files/fcea816f-a16e-42f8-acba-b0d9777c3c72.dcm`

2022-07-26 14:14 UTC, Seunghyeon-lunit commented on insight-viewer.code-workspace
> +}
아 빌드 테스트 중에 잠시 올라갔습니다. PR 시 삭제후 올리도록하겠습니다

2022-07-27 01:00 UTC, deminoth commented
> 만약 px 의 경우 소수점 둘째자리까지 나오는게 어색해보여서 px의 경우 정수형태로 표현하는 것이 어떨까요?

기본값은 소숫점 첫째자리로 부탁드립니다. 나중에 표시를 직접 수정할 수 있는 옵션을 주면 좋을거같네요. (measurement => string 형태의 함수를 넣을 수 있게)

2022-07-27 04:27 UTC, deminoth approved these changes

2022-07-27 05:38 UTC, Seunghyeon-lunit commented
표시를 직접 수정할 수 있는 기능을 추가하였습니다

2022-07-27 06:42 UTC, LTakhyunKim commented
> 표시를 직접 수정할 수 있는 기능을 추가하였습니다

코드 리뷰 시작하기 앞서 위 기능 관련해서 코멘트 남깁니당 ㅠㅠ..
저는 개인적으로 위 기능은 이번 PR 이 아닌 별도의 PR 에서 다뤘으면 합니다.
(위 부분은 상엽님 의견도 듣고 진행하는 것이 좋을 것 같습니다!)

현재 PR 은 특정 DICOM file 에서 일부 정보가 없을 경우 undefined 로 표기되는 버그를 수정하기 위한 목적입니다.
표시 직접 수정 기능의 경우, 구현해주신 사항들을 보았을 때 굉장히 많은 코드를 수정해야하는 것으로 확인됩니다.
관련 타입 추가 및 extends, render component 수정 등 많은 수정 사항이 있기에 그런 것 같네요.

undefined 표기 버그, 단위를 직접 수정할 수 있는 기능 둘 다 작업 범위가 큰 터라 코드 리뷰하기에
꽤 어렵다고 느껴집니다 ㅠㅠ... (요건 아직 제가 코드 리뷰 경험이 부족해서 그런 것 같네요)

2022-07-27 06:50 UTC, Seunghyeon-lunit commented
잘 생각해보면 단위를 직접 수정할 수 있는 기능도 새로운 기능이라 새로운 PR에서 다루는 게 맞는데... 제가 너무 급하게 같이 등록한 것 같네요;; 죄송합니다.

2022-07-27 08:08 UTC, deminoth commented
넵 출력 수정 기능은 코드 그대로 다른 브랜치 생성하여 별도 PR로 리뷰하는게 맞을 것 같습니다.

2022-07-27 13:07 UTC, LTakhyunKim requested changes
승현님~ branch, PR 에는 작업해주신 Jira 티켓을 명시해주시면 감사하겠습니다.
티켓을 직접 옮겨주신 것으로 확인되는데, 위 티켓을 작성해주실 경우 Jira 자동화 시스템으로
넘어가는 것을 확인하실 수 있습니다.

[제가 올린 PR](https://github.com/lunit-io/frontend-components/pull/270) 참고해보시면 도움이 될 것 같습니다.

2022-07-27 13:07 UTC, LTakhyunKim commented on packages/insight-viewer/src/hooks/useMultipleImages/useLoadImages.ts
> +        const newImage = { ...image, _imageSeriesKey } as Image
승현님 위 newImage 선언한 부분이 마음에 걸려서 계속 보고 있는데,
이번 PR 전에서는 이 부분을 굳이 타입단언을 사용하지 않아도 정상적으로 타입 추론이 되는 것으로 확인됩니다.
아래 첨부된 스크린샷을 통해 확인이 가능합니다.

<img width="584" alt="스크린샷 2022-07-27 오후 9 58 22" src="https://user-images.githubusercontent.com/88369343/181252467-83d0a189-30ef-466f-b1bb-fe76fd2761ad.png">

<img width="358" alt="스크린샷 2022-07-27 오후 9 59 48" src="https://user-images.githubusercontent.com/88369343/181252753-489abe17-cce5-4f2a-8998-d06f50d5ed4c.png">

그리고 현재 PR 에서 추론되는 타입 형태입니다.
이전 타입 추론과 다르게 전부 optional 로 되어있는 것을 확인할 수 있습니다.
<img width="439" alt="스크린샷 2022-07-27 오후 10 01 22" src="https://user-images.githubusercontent.com/88369343/181253229-e9b84805-89b2-420b-988e-f25e75b6d68d.png">

현재 전체적인 동작은 문제가 없는 것으로 보이나 이 부분은 확인이 필요할 것 같습니다.

2022-07-27 13:07 UTC, LTakhyunKim commented on packages/insight-viewer/src/utils/cornerstoneHelper/utils.ts
> +>
Image 타입 선언해주셨을 때 data 에 대한 타입을 추가해주신 것으로 확인됩니다.
LoadImage type 선언 시에는 삭제해주셔도 괜찮을 것 같습니다.

2022-07-27 13:18 UTC, LTakhyunKim commented on packages/insight-viewer/src/Viewer/types.ts
>      })
```suggestion
  | (CornerstoneImage & { _imageSeriesKey?: string; data: DataSet })
```
data 에 대한 타입은 위와 같이 선언할 수 있을 것 같습니다

2022-07-28 00:56 UTC, Seunghyeon-lunit commented on packages/insight-viewer/src/utils/common/getCircleRadius.ts
>  }
이 부분은 imagerPixelSpacing 이미지가 currentImage 가 있는 경우에만 생성 가능한 구조이기 때문에 같이 체크하는 경우 타입 에러가 납니다.

2022-07-28 02:56 UTC, LTakhyunKim commented on packages/insight-viewer/src/utils/common/getCircleRadius.ts
>  }
> 이 부분은 imagerPixelSpacing 이미지가 currentImage 가 있는 경우에만 생성 가능한 구조이기 때문에 같이 체크하는 경우 타입 에러가 납니다.

[optional chaining](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining) 으로 확인하면 가능할 것 같습니다!
```js
  const imagerPixelSpacing = currentImage?.data.string(IMAGER_PIXEL_SPACING)

  if (!imagerPixelSpacing || imagerPixelSpacing.length === 0) {
    return { radius: calcRadius(x, y, 1, 1), unit: 'px' }
  }

  const [columnPixelSpacing, rowPixelSpacing] = imagerPixelSpacing.split('\\').map(Number)

  return { radius: calcRadius(x, y, columnPixelSpacing, rowPixelSpacing), unit: 'mm' }
```

2022-07-28 06:04 UTC, Seunghyeon-lunit commented on packages/insight-viewer/src/hooks/useMultipleImages/useLoadImages.ts
> +        const newImage = { ...image, _imageSeriesKey } as Image
이 부분은 Image 가 undefined 인 상태에 대한 처리를 해주니 타입 에러가 사라지긴 하네요

2022-07-28 06:07 UTC, LTakhyunKim commented on packages/insight-viewer/src/hooks/useMultipleImages/useLoadImages.ts
> +        const newImage = { ...image, _imageSeriesKey } as Image
> 이 부분은 Image 가 undefined 인 상태에 대한 처리를 해주니 타입 에러가 사라지긴 하네요

넵 말씀해주신 것처럼 Image 가 undefined 일 경우를 처리해주면 위 타입 에러는 사라지는 것은 확인했습니다.

다만, Image type 은 이번 작업에서 data 에 대한 타입에 대한 추가 변경만 존재하므로,
지금 같이 추론하고 있는 이유를 확인하고 있습니다.
(이전에는 undefined 인 상태에 대한 처리가 없어도 타입 에러가 없어서요..)

2022-07-28 06:08 UTC, Seunghyeon-lunit commented
@LTakhyunKim 님이 남겨주신 리뷰들에 대해서는 모두 확인 후 처리하였습니다. 감사합니다.

2022-07-28 08:59 UTC, deminoth commented
@Seunghyeon-lunit 리뷰 중인 코드를 force-push하시면 수정 후에 보는 사람은 코멘트의 맥락을 파악할 수 없는 문제가 생깁니다. force-push는 코멘트가 달리지 않은 변경사항에 대해서만 제한적으로 해 주세요.

2022-07-28 23:15 UTC, LTakhyunKim commented on packages/insight-viewer/src/hooks/useMultipleImages/types.ts
> +  image: CornerstoneImage & { data: DataSet }
data filed 가 CornerstoneImage 에서 항상 포함하는 요소라면 별도의 타입 선언을 하는 것이 좋을 것 같습니다.
지금과 같은 형태로 사용하는 케이스가 종종 있는 것 같은데 이렇게 사용할 경우 관리가 어려울 것 같네요.

저번에 남겨드렸던 타입 optional 로 추론된 원인은 이 부분 type 을 `Image` 로 지정한 것 때문이군요..

2022-07-28 23:15 UTC, LTakhyunKim commented on packages/insight-viewer/src/hooks/useViewportUpdate.ts
> +  image?: CornerstoneImage
승현님 image field 를 optional 로 변경해주신 이유가 있을까요?
이를 사용하는 `InsightViewer` component 의 `image` 는 타입이 `Image` 로 optional 이 아닌,
undefined 을 포함한 형태로 보입니다. 

즉, image parameter 가 optional 이 아닌 undefined 도 가지고 있는 형태가 지금 타입에서 더 맞는 방향이 아닐까하는 생각이 드네요. 

더불어 위 변경사항은 현재 PR 의 undefined ruler 와 다소 관계가 없는 부분으로 보입니다 ㅠㅠ..
타입 개선 부분은 위 PR 기능 구현에 문제가 없다면 함께 논의한 후 별도의 PR 에서 진행하는 것도 좋을 것 같습니다.

2022-07-29 02:42 UTC, Seunghyeon-lunit commented
탁현님, 남겨주신 리뷰에 대해 모두 수정하였습니다.
남겨주신 리뷰 모두 제가 놓친 부분들 이였네요. 감사합니다

2022-07-29 02:53 UTC, LTakhyunKim approved these changes
고생 많으셨습니다~!

2022-07-29 03:15 UTC, merged