frontend-components 4.0.0 프로젝트 설정
lunit-io/frontend-components pull request #30
Opened 2021-04-05 12:50 UTC by skpark-lunit

Feature
---
- Yarn Workspaces/Lerna를 사용한 Monorepo 구성
- ESLint, Prettier, EditorConfig, Husky를 사용하여 코딩 규칙 적용
- Typescript configuraion

Note
---
기존 Vercel에 적용되어있던 Build command가 빠져있어 오류가 나고 있는데, https://app.asana.com/0/1200128631446379/1200129667050771/f 이 task에서 고칠 예정

2021-04-06 04:53 UTC, yami03 commented
고생많으셨습니다~ 
궁금한점은 master로 머지하게되면 이전 레거시 frontend-components 의 문서가 보고싶거나.. 
레거시코드의 수정이 필요하게 된다면 어떻게 되는지 궁금합니다.

2021-04-06 05:22 UTC, deminoth commented
> 궁금한점은 master로 머지하게되면 이전 레거시 frontend-components 의 문서가 보고싶거나..
레거시코드의 수정이 필요하게 된다면 어떻게 되는지 궁금합니다.

보통 머지 전 시점의 브랜치를 따서 관리하게 됩니당 (1.x 이런 식으로)
문서는 브랜치 프리뷰가 vercel에서 잘 뜨게 약간의 수정은 필요하겠네요

2021-04-06 05:23 UTC, skpark-lunit commented
> 고생많으셨습니다~
> 궁금한점은 master로 머지하게되면 이전 레거시 frontend-components 의 문서가 보고싶거나..
> 레거시코드의 수정이 필요하게 된다면 어떻게 되는지 궁금합니다.

새로 프로젝트를 만들어서 다시 pr 올릴게요. cc. @deminoth

2021-04-06 05:50 UTC, deminoth requested changes
lerna 커맨드 실행해볼수 있게 packages랑 apps 안에 hello world 같은거 넣어주시면 좋을거같아요

2021-04-06 05:50 UTC, deminoth commented on .gitignore
> +.yarn/*
문서 보니까 `!.yarn/patches`도 포함해야 할거같네요
https://next.yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

2021-04-06 05:50 UTC, deminoth commented on package.json
> +  "version": "0.0.0",
4.0.0 달아주세요 (아니면 4.0.0-alpha?)

2021-04-06 06:24 UTC, skpark-lunit commented
> lerna 커맨드 실행해볼수 있게 packages랑 apps 안에 hello world 같은거 넣어주시면 좋을거같아요

네 이번 환경설정 pr 후에 패키지 만들어서 올릴게요.

2021-04-06 06:31 UTC, skpark-lunit commented
> lerna 커맨드 실행해볼수 있게 packages랑 apps 안에 hello world 같은거 넣어주시면 좋을거같아요

일을 끊어서 하고 싶어서, 이번에는 환경설정만 했구요.
이 다음 태스크 https://app.asana.com/0/1200128631446379/1200129667050771/f 에 이어서 패키지, 앱 만들어서 스크립트 돌려볼 수 있게 할게요.
이번에는 husky, lint-staged로 pre-commit시 eslint와 prettier 돌리는 것까지만 확인했습니다.

2021-04-06 06:44 UTC, deminoth approved these changes

2021-04-06 06:46 UTC, deminoth commented
아 혹시 asana task <> github issue 연동하고 싶으시면 unito 쓰시면 됩니다 
https://www.notion.so/lunit/unito-1d22390be20045b788d54e96f21b4a98

2021-04-06 06:54 UTC, yami03 approved these changes

2021-04-07 06:40 UTC, merged

2021-04-07 06:41 UTC, deminoth commented
Vercel은 퍼블릭 사이트 배포 도구인만큼, 4.0에서 Storybook 세팅이 완료된 이후에 사용하는 것으로 하겠습니다.