INSIGHT Viewer 5.8.0 release
lunit-io/frontend-components pull request #304
Opened 2022-09-13 02:30 UTC by LTakhyunKim

## 📝 Description

5.8.0 버전을 릴리즈 합니다.

### Features

Annotation, Measurement 선택 영역 확장 https://github.com/lunit-io/frontend-components/pull/297

### Docs

INSIGHT Viewer docs 리뉴얼 로고 반영 https://github.com/lunit-io/frontend-components/pull/294

### Refactor

Annotation, Measurement 스타일 파일 관리 리팩토링 https://github.com/lunit-io/frontend-components/pull/298

Measurement 좌표계 관련 리팩토링 https://github.com/lunit-io/frontend-components/pull/293, https://github.com/lunit-io/frontend-components/pull/296

Monorepo 디렉토리 구조 개선 https://github.com/lunit-io/frontend-components/pull/291, https://github.com/lunit-io/frontend-components/pull/299

### Bug fix

마우스 이벤트가 제거되어 Drawing 등의 기능이 동작하지 않는 버그 수정 https://github.com/lunit-io/frontend-components/pull/295

## ✔️ PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Chore (non-breaking change which does not affect codebase; Build related changes, version modification, etc.)
- [ ] CI related changes
- [ ] Test Case
- [ ] Performance optimization
- [ ] Site/documentation update
- [ ] Other... Please describe:

## 💣 Is this a breaking change?

- [x] Yes
- [ ] No

2022-09-13 02:40 UTC, LTakhyunKim commented
@deminoth 상엽님 lerna 사용할 때 change log 및 package.json version 업데이트 가능한 커맨드가 있었던 것으로 기억합니다.
https://github.com/lunit-io/frontend-components/blob/master/lerna.json 참고

현재 위와 같은 기능이 nx 에서도 셋업이 되어있는 것일까요?

2022-09-13 02:54 UTC, deminoth commented
> 현재 위와 같은 기능이 nx 에서도 셋업이 되어있는 것일까요?

아직 없습니다 😞 Nx 문서에는 아래와 같이 코멘트되어 있네요

> Right now Nx does not handle version management although you can use the [@jscutlery/semver]
> 
> (https://github.com/jscutlery/semver) Nx plugin.
> 
> You can also leverage a 3rd-party tool such as:
> 
> [release-it](https://github.com/release-it/release-it) (standalone CLI tool)
> [changesets](https://github.com/changesets/changesets) (standalone CLI tool)

2022-09-13 02:57 UTC, LTakhyunKim commented
> > 현재 위와 같은 기능이 nx 에서도 셋업이 되어있는 것일까요?
> 
> 아직 없습니다 😞 Nx 문서에는 아래와 같이 코멘트되어 있네요

넵, 공유해주신 플러그인 바탕으로 change log 생성 및 version 관리해보겠습니다.
해당 PR 에서 작업 이어서 할게요!

2022-09-13 02:58 UTC, LTakhyunKim commented on apps/insight-viewer-docs/containers/HttpHeader/WithJwt.tsx
> +const HTTP_HEADER_AUTHORIZATION = 'Bearer blahblah'
상엽님 예전부터 있던 코드인데, 사실상 mock data 목적으로 표기된 데이터라
큰 문제는 없어보이는데 위 알림은 무시해도 괜찮을까요?

2022-09-13 08:10 UTC, LTakhyunKim commented
@deminoth 상엽님 `Change log 생성` 및 `Viewer library bump` 까지 진행했습니다. [4eb1c39](https://github.com/lunit-io/frontend-components/pull/304/commits/4eb1c390d7f635311a9b680cdca86b1272a1f6e9), [991e5d3](https://github.com/lunit-io/frontend-components/pull/304/commits/991e5d306cd2c1a1583e4393b3dbca90766a2a8b)
다만 하나의 커밋에서 `docs, viewer` 를 한번에 처리하는 방법을 못 찾고 있습니다.
우선 두 개로 분할하여 올리긴 했지만 혹시 방법이 있을까요?

현재 실행한 커맨드는 아래와 같습니다. (프로젝트 별 각자 change log 생성 및 commit 남기는 목적)
`nx run insight-viewer:version --releaseAsminor --commitMessageFormat="chore(release): publish release ${projectName}"`
`nx run insight-viewer-docs:version --releaseAsminor --commitMessageFormat="chore(release): publish release ${projectName}"`

이를 한 번에 실행하기 위해 실행한 커맨드는 아래와 같습니다. 이와 함께 에러 이미지도 첨부드립니다.
`nx affected --target version --releaseAsminor --commitMessageFormat="chore(release): publish release"`
<img width="995" alt="스크린샷 2022-09-13 오후 5 09 15" src="https://user-images.githubusercontent.com/88369343/189847080-369bc7be-c6a9-40d8-a4b1-fce05b155de0.png">

뭔가 이 둘을 병렬로 실행 하면서 충돌이 일어나는거 같은데 해결 방법을 찾기가 어려워 도움 요청 드립니다 ㅠㅠ

2022-09-13 08:25 UTC, deminoth commented on apps/insight-viewer-docs/containers/HttpHeader/WithJwt.tsx
> +const HTTP_HEADER_AUTHORIZATION = 'Bearer blahblah'
네 무시하도록 처리했습니다

2022-09-13 08:27 UTC, deminoth commented
> 뭔가 이 둘을 병렬로 실행 하면서 충돌이 일어나는거 같은데 해결 방법을 찾기가 어려워 도움 요청 드립니다 ㅠㅠ

`--parallel=1` 한번 해보세용 https://nx.dev/nx/affected#parallel

2022-09-13 08:33 UTC, LTakhyunKim commented
> --parallel=1 한번 해보세용 https://nx.dev/nx/affected#parallel

옹.. 우선 이렇게 하게 되면 병렬로 잘 처리되는 것 같은데 음.. 제가 원한 동작이랑 조금은 다르네요 ㅠ..
위 커맨드를 사용하게 되면 아래 이미지와 같이 처리됩니다.
<img width="809" alt="스크린샷 2022-09-13 오후 5 31 07" src="https://user-images.githubusercontent.com/88369343/189852286-b77e2506-5d6a-4b92-b3b5-8118b048d168.png">

저는 기존 동작처럼 아래 이미지와 같이 하나의 커밋에 두 개의 태그가 남는 방향을 고려하고 있습니다.
<img width="792" alt="스크린샷 2022-09-13 오후 5 31 44" src="https://user-images.githubusercontent.com/88369343/189852443-a1368c08-b387-4923-a9ce-4158c3a4b579.png">

아무래도 굳이 별도의 커밋을 남길 필요는 없어보여서요. 혹시 상엽님 생각은 어떠신가요? 
현재의 방식도 괜찮을지 아니면, 이전 방식처럼 하나의 커밋으로 구성되는 것이 좋을지에 의견을 듣고 싶습니당

2022-09-13 08:37 UTC, deminoth commented
> 저는 기존 동작처럼 아래 이미지와 같이 하나의 커밋에 두 개의 태그가 남는 방향을 고려하고 있습니다.

넵 docs를 별도로 버저닝할 필요가 없으니, 하나의 버전으로 진행하는게 저도 맞을 것 같습니다. 이 경우 플러그인의 [synced mode](https://github.com/jscutlery/semver#synced-mode) 사용하면 될거같네요.

2022-09-13 08:42 UTC, LTakhyunKim commented
> 넵 docs를 별도로 버저닝할 필요가 없으니, 하나의 버전으로 진행하는게 저도 맞을 것 같습니다. 이 경우 플러그인의 [synced mode](https://github.com/jscutlery/semver#synced-mode) 사용하면 될거같네요.

넵, 처음에 저 커맨드를 써볼려고 시도해봤는데, 저대로 실행하는 것이 아닌 workspace 에 project 명을 입력하는 것이 아닌가하는 의문이 들어서 다른 방법을 찾고 있었습니다ㅋㅋ.. 일단 다시 시도해보겠습니다!

2022-09-13 09:28 UTC, deminoth commented
> 넵, 처음에 저 커맨드를 써볼려고 시도해봤는데, 저대로 실행하는 것이 아닌 workspace 에 project 명을 입력하는 것이 아닌가하는 의문이 들어서 다른 방법을 찾고 있었습니다ㅋㅋ.. 일단 다시 시도해보겠습니다!

처음 install 할 때 `--syncVersion` 옵션을 써야 한다고 하네요 ㅠㅠ 이놈들 https://github.com/jscutlery/semver/issues/557
`nx g @jscutlery/semver:install --syncVersions` 해보니 `workspace.json` 파일이 정상적으로 업데이트됩니다.
`"tagPrefix": "@lunit/insight-viewer@"`를 `options`에 추가하여주시면 `nx run workspace:version` 정상적으로 실행됩니다.

2022-09-13 09:34 UTC, LTakhyunKim commented
> 처음 install 할 때 --syncVersion 옵션을 써야 한다고 하네요 ㅠㅠ 이놈들 https://github.com/jscutlery/semver/issues/557
다 지우고 nx g @jscutlery/semver:install --syncVersions 해보니 workspace.json 파일이 정상적으로 업데이트됩니다.
"tagPrefix": "@lunit/insight-viewer@"를 options에 추가하여주시면 nx run workspace:version 정상적으로 실행됩니다.

으헝 ㅠㅠ...  찾아주셔서 감사합니다.. 말씀해주신 것처럼 다시 시도해보겠습니다!

2022-09-13 10:00 UTC, LTakhyunKim commented
말씀해주신 방법 토대로 CHANGELOG.md 및 bump 성공했습니다. 🥺 [25e96dc](https://github.com/lunit-io/frontend-components/pull/304/commits/25e96dce993f1efbaaa1694946c105a1474d1db4)

이 밖에 nx 로 이전하면서 이전 CHANGELOG 가 없어진 듯하여 다시 추가했습니다. [c9f9cde](https://github.com/lunit-io/frontend-components/pull/304/commits/c9f9cde15114b1aa5f280156709b919d7fe3854d)

2022-09-13 10:10 UTC, LTakhyunKim commented
추가로 major, minor, patch version release 에 대한 script 도 추가했습니다. [dd5d105](https://github.com/lunit-io/frontend-components/pull/304/commits/dd5d1057d6d6517aaf9372cd86faccbb6f7edaa2)

2022-09-13 11:55 UTC, deminoth approved these changes

2022-09-13 23:35 UTC, deminoth commented
탁현님 #298 에서 AnnotationViewer, MeasurementViewer에 있던 `pointerEvents: 'none';`이 제거되어 Annotation, Measurement가 겹쳐있으면 아래쪽 객체가 선택되지 않는 버그가 다시 발생했습니다. 이 브랜치에서 수정하고 가는게 맞을 것 같네요.

2022-09-13 23:36 UTC, deminoth requested changes
탁현님 https://github.com/lunit-io/frontend-components/pull/298 에서 AnnotationViewer, MeasurementViewer에 있던 pointerEvents: 'none';이 제거되어 Annotation, Measurement가 겹쳐있으면 아래쪽 객체가 선택되지 않는 버그가 다시 발생했습니다. 이 브랜치에서 수정하고 가는게 맞을 것 같네요.

2022-09-13 23:55 UTC, LTakhyunKim commented
> 탁현님 #298 에서 AnnotationViewer, MeasurementViewer에 있던 pointerEvents: 'none';이 제거되어 Annotation, Measurement가 겹쳐있으면 아래쪽 객체가 선택되지 않는 버그가 다시 발생했습니다. 이 브랜치에서 수정하고 가는게 맞을 것 같네요.

넵, 해당 브랜치에서 수정하겠습니다! 제가 금일 병원 일정이 있어 오후 중에 조치할 수 있을 것 같습니다~

2022-09-14 06:42 UTC, LTakhyunKim commented
위 PR 은 5.8.0 버전이 배포됨에 따라 우선 머지하겠습니다. 
이와 더불어 현재 5.8.0 버전에 이슈가 있어 deprecate 후 hotfix 로 5.8.1 배포 진행하겠습니다.

2022-09-14 06:43 UTC, deminoth approved these changes

2022-09-14 06:43 UTC, merged