4.0.0
lunit-io/frontend-components pull request #39
Opened 2021-04-26 05:03 UTC by skpark-lunit

Ticket
---
https://app.asana.com/0/1200128631446379/1200237698436871

Feature
---
- 이미지 로더 선택(Cornerstone WADO Image Loader / Cornerstone Web Image Loader) 적용
  - cornerstone-web-image-loader 패키지 추가 https://github.com/lunit-io/frontend-components/commit/9a852a435073e7a55bced378c14909b8c0d1d783
  - useLoadImage 추가 https://github.com/lunit-io/frontend-components/commit/8f9a06092482508d17dffb2edacdbc1c6c2e0e1a https://github.com/lunit-io/frontend-components/commit/f035c0c733e0213eab125e8f3cab8c8e1f71108b
  - useLoadeImage hook cornerstoneHelper 모듈로 이동 https://github.com/lunit-io/frontend-components/commit/9f70f98c99ee4e660bf4f0d4b6955dffde8cb2f3
  - wado/web 이미지 로더 컴퍼넌트 분리하여 type prop 제거 https://github.com/lunit-io/frontend-components/commit/af21ef494c06e632dc3d8fb56593234ccd577138
- storybook mdx로 작성하기 https://github.com/lunit-io/frontend-components/commit/bbd7a7a8694abb26c30a8aca7bd8b33ca78eb4c9 https://github.com/lunit-io/frontend-components/commit/edc17b72aeba9335cb8d03110d00cc069345a06a
  - 스토리북에 args 추가 https://github.com/lunit-io/frontend-components/commit/1f22b455f78504bf61a91327851d870fe2325ed4
  - 스토리북에 argTable 추가 https://github.com/lunit-io/frontend-components/commit/2a1433ba7318bb3e601747414d111b56c30364cd
- DOM 엘리먼트 사이즈 변경시, 코너스톤 resize
 https://github.com/lunit-io/frontend-components/commit/e93cb045901681bb6d981b18a3b8ddea4e049acc https://github.com/lunit-io/frontend-components/commit/ae5f9794dc1819deaa4aac6d3980ea71d75d90d9 https://github.com/lunit-io/frontend-components/commit/3280a3712ef1aaa33ef3443f56603e05b2d9ec7b
- InsightViewer demo앱에 코드블록 컴퍼넌트 추가
https://github.com/lunit-io/frontend-components/commit/247de83ac6060965a2c100511e6318596c7a939e https://github.com/lunit-io/frontend-components/commit/99f8bf869a974009064b437ac15042891692387b https://github.com/lunit-io/frontend-components/commit/ad0847369fff7c21f1b7de2dffcabbe553e4c81e
- InsightViewer demo앱에서 imageId 변경 테스트 https://github.com/lunit-io/frontend-components/commit/a8a8e30dca30f1fdd8f3c86525beaede43d7c2c4

Next Todo
---
pan/flip/invert

2021-04-26 06:33 UTC, yami03 commented on apps/insight-viewer-demo/src/containers/Basic/index.tsx
> +const vebImageViewercode = `\
web의 오타? 😯

2021-04-26 06:41 UTC, yami03 commented on apps/insight-viewer-demo/src/containers/Basic/index.tsx
> +  return <InsightViewer imageId={WEB_URL} />
`<WebImageViewer />` 이 컴포넌트로 변경 되어야 할거 같습니다~

2021-04-26 07:58 UTC, yami03 commented
![image](https://user-images.githubusercontent.com/36615680/116048819-8cb41880-a6b0-11eb-8d12-1bd4a194ab12.png)
데모 페이지에서 캔버스 위에 빈 div가 있는데 역할이 궁금합니다~

2021-04-26 08:03 UTC, Jiyeon-lunit approved these changes
feature 별 commit id 를 적어주셔서 개발 흐름을 따라가는데 도움이 많이 되었습니다! WebImageViewer 를 type 으로 구분하지 않고 따로 component 로 빼주셔서 이용자가 더 쉽게? 사용할 수 있을 것 같아요.

2021-04-26 08:04 UTC, yami03 commented on apps/insight-viewer-demo/src/containers/Basic/useImageSelect.tsx
> +        <Button colorScheme="blue" onClick={() => handleClick('image3')}>image 3</Button>
소소하게.. 무엇을 클릭했는지 알 수 있으면 좋을거 같아요~

2021-04-26 08:17 UTC, yami03 commented
![image](https://user-images.githubusercontent.com/36615680/116050745-cbe36900-a6b2-11eb-96be-fe7ece5a374e.png)
스토리북에서도 데모페이지와 비슷하게 볼 수 가 있는데 
데모페이지와 스토리북 차이가 무엇이었죠.. 😅 혹시 숙경님이 두번 일하시는 거 아니신가 해서.. 질문드립니다.

2021-04-26 08:23 UTC, deminoth commented on packages/insight-viewer/src/Viewer/index.tsx
> +export function WebImageViewer({ imageId = undefined }: Prop): JSX.Element {
`cornerstone-wado-image-loader`의 경우 이미지 코덱을 포함하고 있다보니 번들 사이즈가 매우 큽니다(약 3~4MB). 이 때문에 `WebImageViewer`만 사용하는 애플리케이션에서 `Viewer` 관련 코드들이 포함되지 않는게 중요할 것 같아요. 그냥 tree-shaking을 믿고 사용하면 되는걸까요? 아니면 애초에 패키지를 분리해두는게 좋을까요?

2021-04-26 08:23 UTC, deminoth commented on packages/insight-viewer/src/Viewer/index.tsx
> +export default function Viewer({ imageId = undefined }: Prop): JSX.Element {
`WebImageViewer`와 대비되게 `DICOMImageViewer`여도 괜찮을거 같습니다. 아니면 `WADOImageViewer`쓸수도 있긴 한데… 사실 로컬 DICOM 파일도 이 로더 타다보니 정확한 명명은 아닐거같아요. (WADO는 Web Access to DICOM Objects의 약자입니다)

2021-04-26 08:23 UTC, deminoth commented on packages/insight-viewer/src/components/Wrapper/index.tsx
> +      <ReactResizeDetector
요거는 좀 낡은 방식이고 문서 보시면 `useResizeDetector` 사용할 수 있습니당

2021-04-26 08:24 UTC, Jiyeon-lunit commented
> ![image](https://user-images.githubusercontent.com/36615680/116048819-8cb41880-a6b0-11eb-8d12-1bd4a194ab12.png)
> 데모 페이지에서 캔버스 위에 빈 div가 있는데 역할이 궁금합니다~

이미 알고 계실수도 있지만 저도 궁금해서 찾아봤는데 이거 아닐까요? 

https://github.com/lunit-io/frontend-components/blob/d3be9ec2017618a1af3442ca3eb10e19ec45aab9/packages/insight-viewer/src/components/Wrapper/index.tsx#L26-L30

2021-04-26 08:26 UTC, deminoth commented
> 데모 페이지에서 캔버스 위에 빈 div가 있는데 역할이 궁금합니다~

이거 아마 react-resize-detector에서 크기 감지용으로 넣어준걸거에요

2021-04-26 09:36 UTC, skpark-lunit commented
> ![image](https://user-images.githubusercontent.com/36615680/116050745-cbe36900-a6b2-11eb-96be-fe7ece5a374e.png)
> 스토리북에서도 데모페이지와 비슷하게 볼 수 가 있는데
> 데모페이지와 스토리북 차이가 무엇이었죠.. 😅 혹시 숙경님이 두번 일하시는 거 아니신가 해서.. 질문드립니다.

현재 기능이 얼마 없는 단순한 컴퍼넌트이다 보니 스토리북과 데모 페이지가 거의 똑같습니다.
스토리북은 컴퍼넌트 props과 그에 따른 디스플레이 가이드가 될 것이고요.
데모 페이지는 컴퍼넌트를 실제 사용하면서 여러가지 상황을 재현해보려고 해요.
스토리북은 다음과 같이 imageId prop에 대한 설명이 나오는데, 여기서는 문자열이고 빨간 *로 필수값임을 알 수 있습니다.
(필수값인데 string | undefined 라고 나오는 부분은 수정해야겠네요.)
<img width="1376" alt="스크린샷 2021-04-26 오후 6 26 56" src="https://user-images.githubusercontent.com/81394944/116060663-07833080-a6bd-11eb-967f-d8cee07eea56.png">
일반적인 컴퍼넌트 스토리북으로 씁니다.

데모 페이지는 InsightViewer 사용자를 위한 가이드이긴 하지만,
개발 중에서는 제가 보기 위한 용도가 더 커요.
다른 앱에서 @lunit/insight-viewer 컴퍼넌트가 잘 통합되는지,
추가적인 UI를 붙여서 엔드유저가 할 것이라고 추측하는 인터랙션을 붙여보고 잘 동작하는지 확인하기 위함입니다.
현재 데모앱에서 image 버튼을 붙여서 이미지를 바꿔보는 테스트를 하는 게 그런 예이지요.

2021-04-26 09:55 UTC, skpark-lunit commented on packages/insight-viewer/src/components/Wrapper/index.tsx
> +      <ReactResizeDetector
게다가 현재 구현에 오류가 있네요. ref 때문에 무한 렌더링 발생하고 있습니다. 버그 픽스하면서 useResizeDetector 사용하겠습니다.

2021-04-26 09:58 UTC, skpark-lunit commented on packages/insight-viewer/src/modules/cornerstoneHelper/useLoadImage.ts
> +  const cornerstoneWebImageLoader = require('cornerstone-web-image-loader')
@deminoth 님, useLoadImage hook에서 이미지 로더 타입에 따라 init을 분리했구요.
이 init에서 cornerstone-wado-image-loader 또는 cornerstone-web-image-loader를 require 하고 있어서,
해당 로더 관련 패키지만 로드한다고 생각했는데, 아닐까요?

2021-04-26 10:01 UTC, deminoth commented
> (필수값인데 string | undefined 라고 나오는 부분은 수정해야겠네요.)

그러면 이미지를 표시하지 않을 때는 undefined 대신 빈 문자열을 쓰나요?

2021-04-26 10:03 UTC, skpark-lunit commented
> > (필수값인데 string | undefined 라고 나오는 부분은 수정해야겠네요.)
> 
> 그러면 이미지를 표시하지 않을 때는 undefined 대신 빈 문자열을 쓰나요?
필수값으로 하면 문제가 될까요?
그렇다면 빈 문자열로 타입을 통일시키는 게 좋을 것 같습니다.

2021-04-26 12:01 UTC, skpark-lunit commented on packages/insight-viewer/src/components/Wrapper/index.tsx
> +      <ReactResizeDetector
https://github.com/lunit-io/frontend-components/pull/39/commits/37d04e4a1feec9ee1fe866121cf002a0302d6d82

2021-04-26 12:27 UTC, yami03 approved these changes

2021-04-26 12:48 UTC, deminoth commented on packages/insight-viewer/src/modules/cornerstoneHelper/useLoadImage.ts
> +  const cornerstoneWebImageLoader = require('cornerstone-web-image-loader')
이게 dynamic require가 아닌 이상 앱 번들에는 포함이 될 것 같아서요. 저도 해봐야 알거같습니다 ㅎㅎ

2021-04-27 00:41 UTC, skpark-lunit commented on packages/insight-viewer/src/modules/cornerstoneHelper/useLoadImage.ts
> +  const cornerstoneWebImageLoader = require('cornerstone-web-image-loader')
말씀하신대로 번들에 포함되고 있습니다. 다음 pr에서 https://app.asana.com/0/0/1200251257893715/f 할게요.

2021-04-27 01:11 UTC, skpark-lunit commented on packages/insight-viewer/src/Viewer/index.tsx
> +export default function Viewer({ imageId = undefined }: Prop): JSX.Element {
https://github.com/lunit-io/frontend-components/pull/39/commits/13dede981a7510cc81aed34016cfbd3b3d7ad042

2021-04-27 01:11 UTC, skpark-lunit commented on apps/insight-viewer-demo/src/containers/Basic/useImageSelect.tsx
> +        <Button colorScheme="blue" onClick={() => handleClick('image3')}>image 3</Button>
https://github.com/lunit-io/frontend-components/pull/39/commits/1ddd98c3ac25fb2d5f3e731416e18548d492f68d

2021-04-27 03:31 UTC, deminoth commented on packages/insight-viewer/src/modules/cornerstoneHelper/useLoadImage.ts
> +  const cornerstoneWebImageLoader = require('cornerstone-web-image-loader')
혹시 asana 불편하시면 github issue 사용하셔도 괜찮습니당

2021-04-27 05:16 UTC, deminoth requested changes

2021-04-27 05:16 UTC, deminoth commented on packages/insight-viewer/src/modules/cornerstoneHelper/useLoadImage.ts
> +  }, [imageId, ref, type])
example app에서 확인해보니 역시나 imageId가 바뀔때마다 dispose와 init을 실행하면서 불필요한 성능저하가 생기네요. `initMap[type]()` 콜은 `type`이 바뀔 때만 해주고, `init(element)`와 `dispose(element)`는 `ref.current`가 바뀔 때만 해주도록 수정이 필요할 것 같습니다. (이 경우 init전에 loadImage가 호출되지 않도록 신경써주셔야 합니당)

아래 스샷은 프로파일링 결과인데 1500ms 부근 스샷에서 뷰어가 검게 변하는 부분이 특히 사용자 경험을 해칠 수 있는 부분이에요. 지금처럼 단일 이미지일 때는 큰 차이가 없는데 tomography 표시를 위해 일련의 이미지를 빠르게 전환할 경우 화면이 빠르게 깜빡이게 될 수 있습니다 ㅠ
<img width="617" alt="스크린샷 2021-04-27 오후 2 07 53" src="https://user-images.githubusercontent.com/495412/116188555-9433fa00-a762-11eb-8562-02a10aa119ef.png">

2021-04-27 07:25 UTC, skpark-lunit commented on packages/insight-viewer/src/modules/cornerstoneHelper/useLoadImage.ts
> +  }, [imageId, ref, type])
프로파일링까지 하면서 도와주셔서 감사합니다 :bow:
useEffect hook을 이렇게 나누어서 관심사 분리했습니다. https://github.com/lunit-io/frontend-components/pull/39/commits/18b6110dbdaec12a271608ac226f7a95ddf35a46
1. cornerstone.enable/cornerstone.disable
2. 이미지로더 init: cornerstoneWADOImageLoader/cornerstoneWebImageLoader
3. cornerstone.loadImage

2021-04-27 11:10 UTC, deminoth approved these changes

2021-04-27 11:21 UTC, merged