Feature/add error status code to custom error
lunit-io/frontend-components pull request #51
Opened 2021-06-03 01:36 UTC by skpark-lunit

Ticket
---
https://app.asana.com/0/1200128631446379/1200307264074788/f

Feature
---
- HTTP 에러 상태 코드 추가 https://github.com/lunit-io/frontend-components/commit/c4bba770dc318f23d9696ff733d62a1a075c79a4
- 커스텀 데모 앱 업데이트 https://github.com/lunit-io/frontend-components/commit/cf6dc5072438feb47bd75e300019d4bc03ae4aad

2021-06-03 06:40 UTC, deminoth requested changes

2021-06-03 06:40 UTC, deminoth commented on packages/insight-viewer/src/hooks/useImageLoader.ts
> +        const err: HTTPError = new Error(e.error.message || e.message)
이 catch 문에서 e가 반드시 `ky` 에러라는 보장은 없지 않나요? 예를 들어 사용자가 imageId에 jpg파일 주소를 넣었다면 `cornerstone`에서 에러가 발생할 것 같습니다.

2021-06-04 00:44 UTC, skpark-lunit commented on packages/insight-viewer/src/hooks/useImageLoader.ts
> +        const err: HTTPError = new Error(e.error.message || e.message)
버그 찾아주셔서 감사합니다. :bowing_woman: https://github.com/lunit-io/frontend-components/pull/51/commits/99e39ff34dfb8f704f8eab4a301fd1f2a3df6d7c

2021-06-04 00:49 UTC, deminoth requested changes

2021-06-04 00:49 UTC, deminoth commented on packages/insight-viewer/src/hooks/useImageLoader.ts
> +        const err: HTTPError = new Error(e?.error?.message ?? e.message)
앗 제 코멘트는 err을 항상 `HTTPError` 타입으로 명명하면 안될거같다는 (HTTP에서 에러가 난게 아닌데 onError 콜백 사용자가 오해할 수 있으므로) 뜻이었습니다!
```ts
import { HTTPError, TimeoutError } from 'ky'
if (e instanceof HTTPError) {
...
} else if (e instanceof TimeoutError) {
...
} else {
…
}
```
이렇게 ky에서 throw한 에러와 그 외의 에러를 구분해서 custom error type을 콜백에 넣어주는게 맞는거같아요.

2021-06-04 01:33 UTC, skpark-lunit commented on packages/insight-viewer/src/hooks/useImageLoader.ts
> +        const err: HTTPError = new Error(e?.error?.message ?? e.message)
적당한 에러 타입 이름이 떠오르지 않아서 안이하게 이름을 지었네요. 
이름 변경했습니다. https://github.com/lunit-io/frontend-components/pull/51/commits/76945fab92b00880881d130c7db4376322e762d1
HTTPError와 일반 에러 모두 커스텀 에러 핸들러에서 처리하되,
HTTPError에만 ståtus가 포함되어 있어, 이것으로 상태에 따른 처리하는 것을 의도합니다.

2021-06-04 02:04 UTC, deminoth approved these changes

2021-06-04 02:06 UTC, merged