Feature/update build script
lunit-io/frontend-components pull request #72
Opened 2021-07-05 09:17 UTC by skpark-lunit

Issue
---
https://app.asana.com/0/1200128631446379/1200520363401292/f

Feature
---
- Do not include cjs format bundle in build output.
- Run package.json script in parallel when possible.

2021-07-05 12:29 UTC, deminoth requested changes

2021-07-05 12:29 UTC, deminoth commented on packages/insight-viewer/package.json
> +    "compile": "microbundle --jsx React.createElement --tsconfig tsconfig.build.json -f modern,esm,cjs",
umd가 빠졌으니 Line 8의 `"unpkg": "dist/index.umd.js",`도 삭제하는게 맞을거같습니다.

2021-07-06 00:54 UTC, skpark-lunit commented on packages/insight-viewer/package.json
> +    "compile": "microbundle --jsx React.createElement --tsconfig tsconfig.build.json -f modern,esm,cjs",
제가 umd를 빼는 것을 cjs로 잘못 뺐네요. 말씀하신 부분 포함해 고칠게요

2021-07-06 01:03 UTC, deminoth approved these changes

2021-07-06 01:41 UTC, merged